# Copyright (c) Florian Maury
# SPDX-License-Identifier: BSD-2-Clause

name: Renovate
on:
  push:
    branches:
      - renovate/** # self-test updates
      - main
  workflow_dispatch:
  schedule:
    - cron: '44 4 * * *'

jobs:
  renovate:
    name: Run Renovate
    runs-on: renovate-at-home
    steps:
      - name: Load renovate repo cache
        uses: https://data.forgejo.org/actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: |
            .tmp/cache/renovate/repository
            .tmp/cache/renovate/renovate-cache-sqlite
            .tmp/osv
          key: repo-cache-${{ github.run_id }}
          restore-keys: |
            repo-cache-
      - id: checkout
        name: Checkout repository
        uses: https://codeberg.org/X_Cli/checkout@097cd845b48cfe9563da542dc8051b01aeb6346d
        with:
          repo-sha256: false
      - name: Run Self-hosted Renovate
        run: renovate --token "${{ secrets.TOKEN }}" --platform forgejo --endpoint "${{ env.FORGEJO_SERVER_URL }}" "${{ env.FORGEJO_REPOSITORY }}"
      - name: Save renovate repo cache
        uses: https://data.forgejo.org/actions/cache/save@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: |
            .tmp/cache/renovate/repository
            .tmp/cache/renovate/renovate-cache-sqlite
            .tmp/osv
          key: repo-cache-${{ github.run_id }}
