# Copyright Florian Maury 2025, 2026
# SPDX-License-Identifier: BSD-2-Clause

name: Renovate
on:
  push:
    branches:
      - renovate/** # self-test updates
      - main
  workflow_dispatch:
  schedule:
    - cron: '44 4 * * *'

jobs:
  renovate:
    name: Run Renovate
    runs-on: renovate-at-home
    steps:
      - name: Load renovate repo cache
        uses: https://code.forgejo.org/actions/cache/restore@v5
        with:
          path: |
            .tmp/cache/renovate/repository
            .tmp/cache/renovate/renovate-cache-sqlite
            .tmp/osv
          key: repo-cache-${{ github.run_id }}
          restore-keys: |
            repo-cache-
      - id: checkout
        name: Checkout repository
        uses: https://code.forgejo.org/actions/checkout@v6
        with:
          repo-sha256: false
      - name: Run Self-hosted Renovate
        run: renovate --token "${{ secrets.TOKEN }}" --platform forgejo --endpoint "${{ env.FORGEJO_SERVER_URL }}" "${{ env.FORGEJO_REPOSITORY }}"
        env:
          GITHUB_COM_TOKEN: "${{ secrets.RENOVATE_GITHUB_COM_TOKEN }}"
      - name: Save renovate repo cache
        uses: https://code.forgejo.org/actions/cache/save@v5
        with:
          path: |
            .tmp/cache/renovate/repository
            .tmp/cache/renovate/renovate-cache-sqlite
            .tmp/osv
          key: repo-cache-${{ github.run_id }}
